version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Gatsby Build
          command: yarn gatsby build
      - run:
          name: Test Build
          command: yarn test
